### PR TITLE
Remove Useless Check for AA Detector

### PR DESCRIPTION
**Pull request by BlackYuzia**
I was talk about this check in #90 issue.

I also repeat this here:
1. **AA can be active after round end** (yep). 
2. AA does not work while round is freeze (because angles of players are freezed too). 
_So we didn't get false-positive results at all._

Also, how I say in #90, all detects only from `not active` rounds. I really didn't know why.
Or did you broke something or my code is shit :eyes:
But I didn't get false positive results when I test this code manualy with rage and non cheaters players.

IDK what happen and also didn't know why your check broke my AA detector.

### CODE REVIEW

**Comment by BeepIsla** [comment]
If you remove the `this.isActiveRound` you should also remove it here

https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/fb403d9da8a8d75f79a95168cd77a76e172632c1/detectors/AntiAim.js#L9

Remove the event listeners here

https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/fb403d9da8a8d75f79a95168cd77a76e172632c1/detectors/AntiAim.js#L13-L15

And remove the event handlers here

https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/fb403d9da8a8d75f79a95168cd77a76e172632c1/detectors/AntiAim.js#L76-L82

**Comment by BlackYuzia** [comment]
@BeepIsla check now

**Comment by BeepIsla** [comment]
Should we enable AA detector during warmup as well?

**Comment by BlackYuzia** [comment]
> Should we enable AA detector during warmup as well?

Yea, why not?

**Comment by BlackYuzia** [comment]
@BeepIsla we can enable by default AA detector or you do not want do that?

**Comment by BeepIsla** [comment]
I will do it later, after testing it for a little bit and then also fix something else.

**Pull request merged**
