### PR TITLE
[WIP] Angles Check for Legit and Rage AA

### PR DESCRIPTION
**Pull request by BlackYuzia**
<details>
  <summary>Old Text</summary>
  
**This method can detect Rage AA by pitch angle.**

Tested on **6 cheaters** **with AA**. All results have 5K+ detects.
Tested on **~10 players** **without rage AA**. All results have <= 20 detects.

Tested on **5 cheaters with legit AA.** All results have <= 20 detects 
> This means what **Angles Check** **for Rage AA** can't detect Legit AA.

@BeepIsla currently I just replace old AA detector. 
I am too lazy for check code for add one more detect :eyes: 
**If you explain how to I do that by my own I do that.**

Oh, one more thing.
I think I would not ingnore **warmup period**.

Will wait feedback from #158 but who knows... 
</details>

**New methods for detect legit and rage AA.**

- [x] Complete tests for **Rage AA Detector** ([file](https://github.com/BlackYuzia/CSGO-Overwatch-Bot/blob/BlackYuzia-experimental-angles-check/detectors/AnglesCheck_LegitAA.js))
- [x] Complete tests for **Legit AA Detector** ([file](https://github.com/BlackYuzia/CSGO-Overwatch-Bot/blob/BlackYuzia-experimental-angles-check/detectors/AnglesCheck_AA.js))

### CODE REVIEW

**Comment by BeepIsla** [comment]
AntiAim's don't exclusively look up, down, or in any specific direction. They *could* be looking in any direction.

**Comment by BlackYuzia** [comment]
I saw only UP and DOWN. 
Legit AA is exclude.

**Comment by BlackYuzia** [comment]
Oh yep. A lot of cheaters would use down AA

**Comment by BlackYuzia** [comment]
@BeepIsla if you have demos where cheaters saw at left, right or any else sides/angles (idk if that can be) share with me.
But currently time we have what we have :thinking: 

This will be working. **Should work.**

**Comment by BlackYuzia** [comment]
@BeepIsla can you too test my both types of new detectors?
I mean Rage and Legit AA detectors from my branch.

**This is still work in progress**

**Comment by BlackYuzia** [comment]
**Tests with Rage AA has been successfully completed.**
**Tests with Legit AA has been failed.**

**Pull request closed without merging**
